blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/toneflix/cuttly-laravel/issues/new?assignees=&labels=question
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/toneflix/cuttly-laravel/issues/new?assignees=&labels=feature
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/toneflix/cuttly-laravel/security/policy
    about: Learn how to notify us for sensitive bugs
