name: Run Tests L10

on:
  workflow_call:
    secrets:
      CUTTLY_API_KEY:
        required: true
      CUTTLY_TEAM_API_KEY:
        required: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.2, 8.3]
        laravel: [10.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, pdo, sqlite, pdo_sqlite, curl, libxml, mbstring, zip, pcntl, bcmath, soap, intl, exif, fileinfo
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Matrix dependencies
        if: ${{ matrix.testbench }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --dev

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: 'Create env file'
        run: |
          touch .env
          echo CUTTLY_API_KEY=${{ secrets.CUTTLY_API_KEY }} >> .env
          echo CUTTLY_TEAM_API_KEY=${{ secrets.CUTTLY_TEAM_API_KEY }} >> .env
          cat .env

      - name: Execute tests
        run: ./vendor/bin/pest --ci --coverage --display-errors --testdox
        env:
          XDEBUG_MODE: coverage
          CUTTLY_API_KEY: ${{ secrets.CUTTLY_API_KEY }}
          CUTTLY_TEAM_API_KEY: ${{ secrets.CUTTLY_TEAM_API_KEY }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/logs/clover.xml
